//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessGuru_Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupActivity()
        {
            this.GymMembers = new HashSet<GymMember>();
        }
    
        public int Id { get; set; }
        public string Desc { get; set; }
        public System.DateTime ScheduledAt { get; set; }
        public int PartnerGroupId { get; set; }
    
        public virtual PartnerGroup PartnerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymMember> GymMembers { get; set; }
    }
}
