//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessGuru_Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.GymMembers = new HashSet<GymMember>();
            this.SessionFeedbacks = new HashSet<SessionFeedback>();
        }
    
        public int Id { get; set; }
        public string SessionName { get; set; }
        public System.DateTime SessionAt { get; set; }
        public bool isCancelled { get; set; }
        public string Desc { get; set; }
        public int TrainerId { get; set; }
    
        public virtual GymMember GymMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymMember> GymMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionFeedback> SessionFeedbacks { get; set; }
    }
}
