//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace FitnessGuru_Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionFeedback
    {
        public int Id { get; set; }

        [Display(Name = "Feedback")]
        public string Desc { get; set; }

        [Display(Name = "Rating")]
        public Nullable<int> Rating { get; set; }
        public int GymMemberId { get; set; }
        public int SessionId { get; set; }
    
        public virtual GymMember GymMember { get; set; }
        public virtual Session Session { get; set; }
    }
}
