//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessGuru_Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerPersonalAppointmentSession
    {
        public int Id { get; set; }
        public System.DateTime AvailableAt { get; set; }
        public int TrainerId { get; set; }
    
        public virtual GymMember GymMember { get; set; }
        public virtual PersonalAppointmentRequest PersonalAppointmentRequest { get; set; }
    }
}
